#__Mini Project 3: Regression Dummy Dataset__

#Step 1: Import Library

In [1]:
import pandas as pd

In [2]:
import numpy as np

#Step 2: Generating Dataset

In [3]:
from sklearn.datasets import make_regression

In [4]:
X, y = make_regression(n_samples=500, n_features=5, coef=False, bias=12, noise=10, random_state=2529)

In [5]:
X, y, z = make_regression(n_samples=500, n_features=5, coef=True, bias=12, noise=10, random_state=2529)

In [6]:
X.shape, y.shape

((500, 5), (500,))

In [7]:
z


array([29.45661718, 60.14529878, 61.7409438 , 13.32437893, 99.08122896])

In [8]:
X.shape, y.shape

((500, 5), (500,))

In [9]:
X[0:5]

array([[ 0.77913208, -1.09701784, -0.14239962,  1.02427891, -1.0708024 ],
       [-0.6925009 ,  0.45535977,  0.34707569, -0.32456746,  0.21970203],
       [-0.03901601, -0.3265115 ,  0.59793721,  0.61686653, -0.6237489 ],
       [-0.61566117, -0.11782129, -0.98234619, -0.78292727,  0.42713048],
       [ 1.30822207, -0.72541559,  0.60187975,  0.33285998,  1.48506184]])

In [10]:
y[0:5]

array([-136.21858395,   49.83118244,  -29.81097858,  -31.74001475,
        193.0687778 ])

In [11]:
X.shape, y.shape

((500, 5), (500,))

#Step 3: Splitting Data

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=2529)

In [14]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((350, 5), (150, 5), (350,), (150,))

#Step 4: Creating model

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model = LinearRegression()

#Step 5: Training Model

In [17]:
model.fit(X_train, y_train)

LinearRegression()

#Step 6: Getting Intercepts and Coefficients

In [18]:
model.intercept_

12.804677404011848

In [19]:
model.coef_

array([30.14690156, 59.8508539 , 61.00591796, 13.33058614, 98.52732683])

#Step 7: Prediction Model

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred.shape

(150,)

In [22]:
y_pred

array([ -32.2347268 ,  -91.78838198, -111.32428609,   32.28900762,
       -292.09184678,  232.80381314,   45.45589568, -206.64663509,
       -234.70619469,  -99.53722469,  109.51230639, -112.24192419,
        136.86734982,    9.50169605, -402.91778394,  -77.75468931,
         31.16247075,  -11.08354812,   31.85126688,   37.4989766 ,
        -33.17312782,  165.96248357,  136.44084324,   43.71369762,
        169.91060611, -255.66815548,   -6.97645701, -115.23137387,
        -27.09548272,   -2.27310513,  -97.06342353,   57.62031761,
        185.7350271 ,  -60.45930909,   11.20091455,  176.09294043,
         90.16023475,  121.22117973,  -12.7823069 ,  -46.97799373,
         84.74765683,   38.71436232,  -71.35539323,   -1.53368019,
        -30.73878351,   54.71398149,  -21.39863976, -272.82340302,
       -118.65913112,  -38.95749518,  -56.94266543,  -64.97208225,
         83.15562417,   84.93116766, -118.46836522,  181.58821651,
        -49.51641057,  -21.16415589,   24.61247158,   15.50449

#Step 8: Accuracy

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score

In [24]:
mean_squared_error(y_test, y_pred)

93.17298608096334

In [25]:
mean_absolute_error(y_test, y_pred)

7.861503882499261

In [26]:
mean_absolute_percentage_error(y_test, y_pred)

0.5394385232604642

In [27]:
r2_score(y_test, y_pred)

0.9944221597296871

#Link of the same: https://colab.research.google.com/drive/1fBrCDUFl0UNMnsxnY8ANZ21unKKR72a4?usp=sharing